rvm:
  - 2.0
  - 2.1.7
  - 2.2.3
  - 2.3.1
addons:
  apt:
    packages:
      - postgresql-server-dev-9.3
  postgresql: "9.3"
services:
  - posgresql
before_script:
  - "mysql -e 'create database lokka_test;'"
  - "psql -c 'create database lokka_test;' -U postgres"
env:
  - DATABASE_URL="mysql://0.0.0.0/lokka_test"
  - DATABASE_URL="postgres://postgres@127.0.0.1/lokka_test"
  - DUMMY=DUMMY # sqlite
notifications:
  irc: "irc.freenode.org#lokka"
  irc: "irc.freenode.org#lokka-ja"
